"""Web API for anchor-align.

Uploads audio + a human-edited transcript, runs the full pipeline
(transcribe -> align -> segment -> QC), and returns the complete result as
JSON: per-word alignment for the transcript heatmap, the produced cues, the
QC findings, and ready-to-download VTT/SRT/confidence artifacts. This is a
thin wiring layer exactly like demo/app.py — every call is into the
pipeline stages as their own tests exercise them.

Dev:  uvicorn web.api:app --port 8000   (Vite dev server proxies /api -> 8000)
Prod: serves web/ui/dist when it exists.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import shutil
import statistics
import tempfile
import threading
import time
import typing
import uuid
from contextlib import asynccontextmanager, suppress
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, Request, Response, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

from anchor_align.export.qc import format_confidence_json
from anchor_align.export.srt import format_srt
from anchor_align.export.vtt import format_vtt
from anchor_align.ingest.document import parse_transcript
from anchor_align.models import MatchType, STTOptions
from anchor_align.normalize.normalizer import DoubleMetaphoneEncoder
from anchor_align.pipeline import align_to_cues
from anchor_align.stt.cache import cached_transcribe
from anchor_align.stt.faster_whisper_adapter import FasterWhisperAdapter

logger = logging.getLogger("anchor_align.web")

REPO_ROOT = Path(__file__).resolve().parent.parent
CACHE_DIR = Path(os.environ.get("ANCHOR_ALIGN_CACHE_DIR", REPO_ROOT / ".cache" / "transcriptions"))
UPLOAD_DIR = REPO_ROOT / ".cache" / "uploads"
SAMPLE_AUDIO = REPO_ROOT / "data" / "sample" / "sample_audio.mp3"
SAMPLE_TRANSCRIPT = REPO_ROOT / "data" / "sample" / "sample_transcript.txt"
UI_DIST = Path(__file__).resolve().parent / "ui" / "dist"

MODELS = ("tiny", "base", "small", "medium")
AUDIO_EXTS = {".wav", ".mp3", ".m4a", ".mp4", ".flac", ".ogg"}
TRANSCRIPT_EXTS = {".txt", ".docx"}
_AUDIO_TTL_S = 60 * 60  # uploaded audio is kept for playback for one hour

# Upload limits: configurable max per-file size, enforced (a) by a middleware
# that rejects a declared Content-Length before the body is consumed, and
# (b) per chunk while streaming the parsed parts to disk - so an oversized
# body never needs to be fully buffered first. UploadFile.file is a
# disk-backed SpooledTemporaryFile past ~1 MB, but .read() would still slurp
# it into RAM (see _stream_to_disk).
MAX_UPLOAD_BYTES = int(os.environ.get("MAX_UPLOAD_BYTES", str(1 << 30)))  # 1 GiB default
_UPLOAD_BUFFER = 1 << 20  # 1 MiB streaming buffer
_MULTIPART_SLACK = 4 << 20  # multipart framing + the small transcript

# Large synthetic fixture — DEV ONLY. The payload JSON is generated by
# web/scripts/make_fixture.py into .cache/fixtures/ (gitignored, so it is
# never part of a build artifact), and the route 404s unless
# ALLOW_FIXTURES=1 is set, so a production deploy cannot reach it.
ALLOW_FIXTURES = os.environ.get("ALLOW_FIXTURES") == "1"
FIXTURE_JSON = REPO_ROOT / ".cache" / "fixtures" / "large.json"
FIXTURE_WAV = REPO_ROOT / ".cache" / "fixtures" / "large.wav"
FIXTURE_GENERATOR = REPO_ROOT / "web" / "scripts" / "make_fixture.py"



@asynccontextmanager
async def lifespan(_: FastAPI) -> typing.AsyncIterator[None]:
    """Warm the default model off the event loop so the first job (and the
    readiness check) does not pay the load. A failed warm-up logs and keeps
    the server up — readiness then reports model_resident=false and the
    first job with that model surfaces the real error."""
    try:
        # _get_adapter only creates the (lazy) adapter — force the actual
        # WhisperModel load so the first job doesn't pay it. _load_model is
        # the adapter's own lazy loader (same project).
        adapter = _get_adapter(DEFAULT_MODEL)
        await asyncio.to_thread(adapter._load_model)  # keep the loop free during load
    except Exception:  # noqa: BLE001 - startup must not die on a model issue
        logger.exception("could not warm faster-whisper model %s", DEFAULT_MODEL)
    yield


app = FastAPI(title="anchor-align", version="0.1.0", lifespan=lifespan)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://127.0.0.1:5173", "http://localhost:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)
# The fixture/align payloads are mostly repeated JSON keys; gzip them for
# the wire. Responses under 1 KB are left alone.
app.add_middleware(GZipMiddleware, minimum_size=1000)


@app.middleware("http")
async def _reject_oversized_bodies(request: Request, call_next):
    """Reject a declared-oversized multipart body before the parser consumes
    it, so nothing is buffered. Requests without a Content-Length (chunked)
    fall through to the per-chunk check in _stream_to_disk."""
    length = request.headers.get("content-length")
    if length is not None and length.isdigit() and int(length) > MAX_UPLOAD_BYTES + _MULTIPART_SLACK:
        return JSONResponse(
            status_code=413,
            content={
                "detail": {
                    "code": "UPLOAD_TOO_LARGE",
                    "message": f"Upload exceeds the maximum allowed size ({MAX_UPLOAD_BYTES} bytes).",
                    "max_bytes": MAX_UPLOAD_BYTES,
                }
            },
        )
    return await call_next(request)

# Injectable clock so the TTL tests can advance past _AUDIO_TTL_S
# without sleeping.
_now = time.time

# --- Model lifecycle: one adapter per model size, process-wide -----------
# FasterWhisperAdapter loads its WhisperModel lazily on the first transcribe
# (faster_whisper_adapter.py:32). Constructing one adapter per request meant
# every transcription-cache MISS paid a full model load, and N concurrent
# uploads held N model copies (medium is ~1.5 GB). The adapter is cached per
# model size; the default is warmed in the lifespan handler below.
#
# Thread safety: CTranslate2's engine releases the GIL and supports
# concurrent calls from multiple Python threads (docs/parallel.md), but that
# statement covers only the engine — faster-whisper's Python wrapper (lazy
# model init in _load_model, tokenizer, feature extraction) is not
# documented as thread-safe, so transcribe() is serialized per model with a
# lock. Cost is negligible: transcription is CPU-bound anyway.
DEFAULT_MODEL = "base"
_adapters: dict[str, FasterWhisperAdapter] = {}
_adapter_locks: dict[str, threading.Lock] = {}
_adapters_guard = threading.Lock()

# Bounded concurrency gate: at most K pipelines run at once, so K uploads
# cannot spawn K model loads. K=2 on this box (16 threads / 32 GB): two
# medium models resident (~3 GB) plus the process stays comfortably under
# memory, and the transcribe lock already serializes CPU-bound
# transcription, so the gate bounds model loads and resident model memory,
# not CPU. A third concurrent upload waits on the semaphore inside the
# threadpool — the event loop stays free because /api/align is `def`.
_GATE = threading.Semaphore(2)


def _get_adapter(model: str) -> FasterWhisperAdapter:
    """Return the process-level adapter for `model`, loading it once."""
    adapter = _adapters.get(model)
    if adapter is not None:
        return adapter
    with _adapters_guard:
        adapter = _adapters.get(model)
        if adapter is None:
            adapter = FasterWhisperAdapter(model_size=model)
            _adapters[model] = adapter
            _adapter_locks[model] = threading.Lock()
    return adapter

# id -> (path, expires_at) for audio served back to the browser for playback
#
# TTL design: entries expire after _AUDIO_TTL_S and the reaper (run on each
# registration) deletes both the registry entry and the file on disk. The
# /api/sample payloads are cached permanently, but the audio_id they bake in
# is TTL-bound — so on every cache hit the sample routes re-register the
# audio when the cached id is no longer live. Three options were considered:
#   1. exempt the sample from the TTL — simplest, but pins sample audio on
#      disk indefinitely and splits lifetime semantics between uploads and
#      samples (the reaper would need a non-expiring marker anyway).
#   2. drop the payload cache and rebuild per request — cheap for the
#      bundled sample (transcription is diskcached), but the fixture payload
#      is a static JSON with no diskcache layer underneath, so the option
#      does not even apply to it, and it would regenerate VTT/SRT/
#      confidence strings on every request for nothing.
#   3. (chosen) re-register on a cache hit when the cached id is missing
#      from the registry, and rewrite it. One membership check per serve, a
#      file copy only after the TTL has elapsed and a reap has happened.
#      Cost: a second copy of the sample audio (271 KB, or the dev-only
#      19 MB fixture) after each expiry — negligible, and self-healing: the
#      reaper purges the stale file, the next serve re-registers a fresh one.
#
# SINGLE-WORKER ONLY: the registry is process-local, so under
# `uvicorn --workers N` an id registered in worker A is invisible to
# worker B and /api/audio/{id} 404s. A shared store (filesystem layout keyed
# by id, or a database) is required before multi-worker deployment; tracked
# as issue #4.
_audio_registry: dict[str, tuple[Path, float]] = {}
# audio_id -> download artifacts (vtt/srt/confidence strings), reaped with
# the audio entry. The align response carries only byte sizes; the content
# is served by GET /api/download/{audio_id}/{fmt}.
_downloads: dict[str, dict[str, str]] = {}
_sample_payload: dict | None = None
_sample_download_content: dict[str, str] = {}
_fixture_download_content: dict[str, str] = {}


def _stream_to_disk(source: typing.BinaryIO, dest: Path) -> int:
    """Stream an uploaded part (the UploadFile.file spool) to dest in
    bounded chunks instead of slurping it into RAM with .read(). Enforces
    MAX_UPLOAD_BYTES while streaming; the temp dir is cleaned up by the
    caller's context."""
    size = 0
    with dest.open("wb") as out:
        while True:
            chunk = source.read(_UPLOAD_BUFFER)
            if not chunk:
                break
            size += len(chunk)
            if size > MAX_UPLOAD_BYTES:
                raise HTTPException(
                    413,
                    detail={
                        "code": "UPLOAD_TOO_LARGE",
                        "message": f"Upload exceeds the maximum allowed size ({MAX_UPLOAD_BYTES} bytes).",
                        "max_bytes": MAX_UPLOAD_BYTES,
                    },
                )
            out.write(chunk)
    return size


def _register_audio(src: Path) -> str:
    now = _now()
    for aid, (path, expires) in list(_audio_registry.items()):
        if expires < now:
            _audio_registry.pop(aid, None)
            _downloads.pop(aid, None)
            # The registry holds the real destination path (id + suffix,
            # e.g. "abc123.wav"). Unlinking the bare id would never match
            # and missing_ok=True would swallow the miss, leaking the file
            # to disk permanently.
            with suppress(OSError):
                path.unlink(missing_ok=True)
    UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
    aid = uuid.uuid4().hex[:16]
    dest = UPLOAD_DIR / f"{aid}{src.suffix.lower()}"
    shutil.copy2(src, dest)
    _audio_registry[aid] = (dest, now + _AUDIO_TTL_S)
    return aid


def _build_payload(
    *,
    audio_name: str,
    transcript_name: str,
    model: str,
    phonetic: bool,
    audio_id: str,
    audio_duration_s: float,
    elapsed_s: float,
    result,
) -> dict:
    edited_order = sorted(result.aligned, key=lambda w: w.token.index)
    aligned = [
        {
            "text": w.token.text,
            "index": w.token.index,
            "char_offset": w.token.char_offset,
            "sentence_id": w.token.sentence_id,
            "is_sentence_end": w.token.is_sentence_end,
            "match_type": w.match_type.value,
            "confidence": round(w.confidence, 4),
            "start": round(w.start, 3),
            "end": round(w.end, 3),
        }
        for w in edited_order
    ]
    cues = [
        {
            "index": c.index,
            "start": round(c.start, 3),
            "end": round(c.end, 3),
            "lines": list(c.lines),
        }
        for c in result.cues
    ]
    issues = [
        {"severity": i.severity, "code": i.code.value, "message": i.message, "cue_index": i.cue_index}
        for i in result.issues
    ]
    confidences = [w.confidence for w in result.audio_order]
    stats = {
        "cues": len(result.cues),
        "qc_errors": result.error_count,
        "qc_warnings": result.warning_count,
        "interpolated_words": sum(1 for w in result.aligned if w.match_type == MatchType.INTERPOLATED),
        "mean_confidence": round(statistics.mean(confidences), 4) if confidences else None,
    }

    # Downloads are the golden-tested export formats (src/anchor_align/export)
    # built server-side — duplicating VTT/SRT formatting in the browser would
    # create a second, untested source of truth for caption formatting. The
    # content is kept out of the align response (it would double-quote-escape
    # JSON inside JSON) and served by GET /api/download/{audio_id}/{fmt};
    # the payload carries only byte sizes so the UI can show file sizes
    # without fetching.
    downloads = {
        "vtt": format_vtt(result.cues),
        "srt": format_srt(result.cues),
        "confidence": format_confidence_json(result.cues, result.audio_order),
    }
    payload = {
        "audio_id": audio_id,
        "audio_name": audio_name,
        "transcript_name": transcript_name,
        "model": model,
        "phonetic": phonetic,
        "elapsed_s": round(elapsed_s, 2),
        "audio_duration_s": round(audio_duration_s, 3),
        "stats": stats,
        "aligned": aligned,
        "cues": cues,
        "issues": issues,
        "downloads": {fmt: len(content) for fmt, content in downloads.items()},
    }
    return payload, downloads


def _run_pipeline(audio_path: Path, transcript_path: Path, model: str, phonetic: bool):
    with _GATE:  # bounded concurrency: K uploads cannot spawn K model loads
        return _run_pipeline_gated(audio_path, transcript_path, model, phonetic)


def _run_pipeline_gated(audio_path: Path, transcript_path: Path, model: str, phonetic: bool):
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    adapter = _get_adapter(model)  # process-level cache: model loaded once per size
    with _adapter_locks[model]:  # faster-whisper wrapper is not documented thread-safe
        transcription = cached_transcribe(
            audio_path,
            f"faster-whisper-{model}",
            adapter,
            STTOptions(),
            cache_dir=CACHE_DIR,
        )
    edited_tokens = parse_transcript(transcript_path)
    result = align_to_cues(
        transcription.words,
        edited_tokens,
        phonetic_encoder=DoubleMetaphoneEncoder() if phonetic else None,
    )
    return transcription, result


def _model_files_present(model: str) -> bool:
    """Do the model's files exist in faster-whisper's HF-hub cache? Mirrors
    the hub layout (models--Systran--faster-whisper-<size>); a cheap stat."""
    hub = Path.home() / ".cache" / "huggingface" / "hub" / f"models--Systran--faster-whisper-{model}"
    return hub.is_dir()


@app.get("/api/health")
async def health() -> dict:
    """Liveness + readiness, cheap enough to answer during an in-flight job
    (async, so it runs on the event loop while jobs occupy the threadpool).

    - model_resident: the adapter (and its WhisperModel) is loaded.
    - offline_satisfiable: with HF_HUB_OFFLINE=1 the model files must exist
      locally; without it a download is possible (assumed satisfiable).
    - cache_dir_writable: the transcription diskcache can open its sqlite.
    ready = loadable model AND writable cache.
    """
    # _model is the adapter's lazily-loaded WhisperModel (same project)
    adapter = _adapters.get(DEFAULT_MODEL)
    resident = adapter is not None and adapter._model is not None
    offline = os.environ.get("HF_HUB_OFFLINE") == "1"
    files_present = _model_files_present(DEFAULT_MODEL)
    offline_satisfiable = (not offline) or files_present
    cache_writable = CACHE_DIR.is_dir() and os.access(CACHE_DIR, os.W_OK)
    return {
        "status": "ok",
        "ready": (resident or offline_satisfiable) and cache_writable,
        "checks": {
            "model_resident": resident,
            "offline_mode": offline,
            "model_files_present": files_present,
            "offline_satisfiable": offline_satisfiable,
            "cache_dir_writable": cache_writable,
        },
    }


@app.post("/api/align")
def align(
    audio: UploadFile = File(...),  # noqa: B008 - FastAPI idiomatic
    transcript: UploadFile = File(...),  # noqa: B008 - FastAPI idiomatic
    model: str = Form("base"),
    phonetic: bool = Form(False),
) -> dict:
    audio_ext = Path(audio.filename or "").suffix.lower()
    transcript_ext = Path(transcript.filename or "").suffix.lower()
    if audio_ext not in AUDIO_EXTS:
        raise HTTPException(400, detail={"code": "INVALID_UPLOAD", "message": f"audio must be one of {sorted(AUDIO_EXTS)} (got '{audio.filename}')"})
    if transcript_ext not in TRANSCRIPT_EXTS:
        raise HTTPException(400, detail={"code": "INVALID_UPLOAD", "message": f"transcript must be one of {sorted(TRANSCRIPT_EXTS)} (got '{transcript.filename}')"})
    if model not in MODELS:
        raise HTTPException(400, detail={"code": "INVALID_UPLOAD", "message": f"model must be one of {list(MODELS)} (got '{model}')"})

    started = time.time()
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        audio_path = tmp_dir / f"audio{audio_ext}"
        _stream_to_disk(audio.file, audio_path)
        transcript_path = tmp_dir / f"transcript{transcript_ext}"
        _stream_to_disk(transcript.file, transcript_path)
        try:
            transcription, result = _run_pipeline(audio_path, transcript_path, model, phonetic)
        except Exception as exc:  # noqa: BLE001 - logged server-side, never leaked
            logger.exception("pipeline failed for %s", audio.filename)
            raise HTTPException(
                500,
                detail={
                    "code": "PIPELINE_FAILED",
                    "message": "The alignment pipeline failed while processing your files. Please try again.",
                },
            ) from exc
        audio_id = _register_audio(audio_path)
        payload, downloads = _build_payload(
            audio_name=audio.filename or "audio",
            transcript_name=transcript.filename or "transcript",
            model=model,
            phonetic=phonetic,
            audio_id=audio_id,
            audio_duration_s=transcription.audio_duration,
            elapsed_s=time.time() - started,
            result=result,
        )
        _downloads[audio_id] = downloads
        return payload


_large_payload: dict | None = None


def _load_large_fixture() -> dict:
    """Serve the 9,000-word synthetic fixture (dev only, ALLOW_FIXTURES=1)."""
    global _large_payload
    global _fixture_download_content
    if _large_payload is None:
        if not FIXTURE_JSON.exists():
            import subprocess
            import sys

            subprocess.run([sys.executable, str(FIXTURE_GENERATOR)], check=True, cwd=str(REPO_ROOT))
        _large_payload = json.loads(FIXTURE_JSON.read_text(encoding="utf-8"))
        _fixture_download_content = _large_payload.pop("download_content", {})
    # Same TTL refresh as the bundled sample: the cached payload must never
    # outlive its audio entry (see the comment above _audio_registry).
    if _large_payload["audio_id"] not in _audio_registry:
        _large_payload["audio_id"] = _register_audio(FIXTURE_WAV)
    _downloads[_large_payload["audio_id"]] = _fixture_download_content
    return _large_payload


@app.get("/api/sample")
def sample(fixture: str | None = None) -> dict:
    """Run the bundled sample pair (data/sample) through the full pipeline
    and return the same payload shape as /api/align. Computed once, cached
    in memory afterwards. ?fixture=large serves the synthetic scale-test
    fixture, gated by ALLOW_FIXTURES=1 (dev only)."""
    if fixture == "large":
        if not ALLOW_FIXTURES:
            raise HTTPException(404, detail={"code": "FIXTURES_DISABLED", "message": "fixtures are disabled (set ALLOW_FIXTURES=1 in dev)"})
        return _load_large_fixture()
    global _sample_payload
    if _sample_payload is None:
        started = time.time()
        try:
            transcription, result = _run_pipeline(SAMPLE_AUDIO, SAMPLE_TRANSCRIPT, "base", False)
        except Exception as exc:  # noqa: BLE001
            logger.exception("sample pipeline failed")
            raise HTTPException(
                500,
                detail={
                    "code": "PIPELINE_FAILED",
                    "message": "The alignment pipeline failed. Please try again.",
                },
            ) from exc
        audio_id = _register_audio(SAMPLE_AUDIO)
        global _sample_download_content
        _sample_payload, _sample_download_content = _build_payload(
            audio_name=SAMPLE_AUDIO.name,
            transcript_name=SAMPLE_TRANSCRIPT.name,
            model="base",
            phonetic=False,
            audio_id=audio_id,
            audio_duration_s=transcription.audio_duration,
            elapsed_s=time.time() - started,
            result=result,
        )
    # The payload cache is permanent but the audio entry is TTL-bound: if
    # the cached id was reaped (an upload after an hour of uptime), register
    # a fresh copy and rewrite the id so the sample never serves a dead one.
    if _sample_payload["audio_id"] not in _audio_registry:
        _sample_payload["audio_id"] = _register_audio(SAMPLE_AUDIO)
    _downloads[_sample_payload["audio_id"]] = _sample_download_content
    return _sample_payload


_DOWNLOAD_MEDIA = {
    "vtt": ("text/vtt", ".vtt"),
    "srt": ("application/x-subrip", ".srt"),
    "confidence": ("application/json", ".confidence.json"),
}


@app.get("/api/download/{audio_id}/{fmt}")
def download(audio_id: str, fmt: str) -> Response:
    """Serve a previously generated download artifact for an alignment.
    The artifact strings are built once at align time (by the golden-tested
    exporters), stored keyed by audio_id, and reaped with the audio entry."""
    media = _DOWNLOAD_MEDIA.get(fmt)
    if media is None:
        raise HTTPException(404, detail={"code": "DOWNLOAD_NOT_FOUND", "message": f"unknown download format {fmt!r}"})
    content = _downloads.get(audio_id, {}).get(fmt)
    if content is None:
        raise HTTPException(404, detail={"code": "DOWNLOAD_NOT_FOUND", "message": "download not found or expired"})
    media_type, suffix = media
    return Response(
        content=content,
        media_type=media_type,
        headers={"Content-Disposition": f'attachment; filename="captions{suffix}"'},
    )


@app.get("/api/audio/{audio_id}")
def audio(audio_id: str) -> FileResponse:
    entry = _audio_registry.get(audio_id)
    if entry is None:
        raise HTTPException(404, detail={"code": "AUDIO_NOT_FOUND", "message": "audio not found or expired"})
    path, _ = entry
    return FileResponse(path)


if UI_DIST.exists():
    app.mount("/", StaticFiles(directory=UI_DIST, html=True), name="ui")
